---
title: "Owner Analysis"
format: html
editor: visual
author: Annie
---

## Exercise: Explore, Clean, and Wrangle Data
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```
```{r}
lobster_abundance <- read_csv(here::here("data/Lobster_Abundance_All_Years_20220829.csv"))
```
```{r}
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))

head(lobster_abundance)
```
```{r}
not_napl <- lobster_abundance %>% 
    filter(SITE != "NAPL")

head(not_napl)
```
```{r}
aque_70mm <- lobster_abundance %>% 
    filter(SITE == "AQUE" & SIZE_MM >= 70)

head(aque_70mm)
```
## Exercise: Data Visualization
```{r}
ggplot(data = lobster_abundance, aes(x = SIZE_MM)) +
    geom_histogram() +
    facet_wrap(~SITE)
```
```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())

head(lobsters_summarize)
```

```{r}
# line plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_line(aes(color = SITE)) 
```

```{r}
# line and point plot
Abundance <- ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE)) + 
  theme_grey()
```
```{r}
ggsave("figs/Abundance.png")
```

